# Matrices

A **matrix** $A$ is a table of scalars. You can think of a matrix as a bunch of column vectors of the same size stacked next to each other (preferred for now), or a bunch of row vectors stacked on top of each other (for later). For example:

$$ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} $$ 

The **shape** of a matrix refers to the number of rows and columns. If $A$ has $m$ rows and $n$ columns, we say that it is an $m \times n$ matrix ("$m$ by $n$").

We use 2D arrays in NumPy to implement matrices. Unfortunately, in NumPy, a 2D array is implemented as a stack of rows, rather than a list of columns.

**IMPORTANT**: a 1D array in NumPy is *not the same* as a 2D array in NumPy that only has one column.

In [1]:
import numpy as np # don't forget this

# matrices are represented as 2D arrays in numpy
# defined in the same manner as 1D arrays, but using double-nested lists
A = np.array([[1,2,3],
              [4,5,6]])
print("The matrix A:\n", A)
print("The shape of A:", A.shape)

v = np.array([7,8,9])
my_row = np.array([[7,8,9]])
my_column = my_row.T  # 'transpose': a convenient way to turn rows to columns, and columns to rows

print("1D array:", v, "with shape", v.shape)
print("2D array with one row: ", my_row, "with shape", my_row.shape)
print("2D array with one column:\n", my_column)
print("with shape", my_column.shape)


The matrix A:
 [[1 2 3]
 [4 5 6]]
The shape of A: (2, 3)
1D array: [7 8 9] with shape (3,)
2D array with one row:  [[7 8 9]] with shape (1, 3)
2D array with one column:
 [[7]
 [8]
 [9]]
with shape (3, 1)


## Notation and Indexing

We usually use upper-case letters as variable names for matrices. Two subscripts are used to *index* the components of a matrix. The first refers to the row, and the second refers to the column. From the matrix $A$ defined above, $A_{1,1} = 1$ and $A_{2,3} = 6$.

(Don't forget that Python uses 0-indexing.)

In [2]:
print("Component of A in first row and first column =", A[0,0])   # again use brackets, but with two indices
print("Component of A in second row and third column =", A[1][2])  # or use two sets of brackets, one for each index

Component of A in first row and first column = 1
Component of A in second row and third column = 6


## Indexing rows and columns (NumPy)

NumPy allows one to select a particular row or column of a matrix.

A single `:` indicates the extraction of the *entire* row or column. It may look complicated, but just keep in mind that you are separately indexing the rows and then from those, the columns.

In [3]:
print("First row of A: ", A[0])    # indexing a matrix with a single number returns a row
print("Second row of A: ", A[1,:])  # it is clearer if you also include a : in the second index
print("Third column of A: ", A[:,2])


First row of A:  [1 2 3]
Second row of A:  [4 5 6]
Third column of A:  [3 6]


In [4]:
print(A[:,0:2])   # columns between first and (but not including) third column
print(A[1,0::2])  # second row, every 2 columns starting from first column
print(A[-1,1:])   # last row, all columns starting with the second

[[1 2]
 [4 5]]
[4 6]
[5 6]


## Manipulation (NumPy)

As with vectors, matrices can be manipulated by changing their entries, adding new rows or columns, or deleting existing rows or columns. Changing entries is straightforward and works in the same way as vectors. Use indexing to specify which entries you want to change and place that on the LHS of an equals sign, and place the actual values you want on the RHS.

The same functions we showed for vectors work for matrices, but we have to be careful in making sure that the dimensions match up. For example, adding a row only works if it is the same size as the number of columns in the matrix. (Again, the one exception is if you add a scalar, where NumPy automatically fills out the correctly sized row or column with the same value.) The `axis` parameter can be used to specify whether we are manipulating a matrix's rows or columns.

In [5]:
A[0,0] = 0                              # set A[0,0] to 0
A[:,1:] = np.array([[-2,-3], [-5,-6]])  # change columns start with the second column
print(A)

print(np.insert(A, 0, [6,7,8], axis=0)) # a new matrix starting from A where we insert new first row
print(np.insert(A, 2, 10, axis=1))      # a new matrix starting from A where we insert new third column, with all components equal to 10
print(np.delete(A, 1, axis=1))          # a new matrix starting from A where we delete second column

[[ 0 -2 -3]
 [ 4 -5 -6]]
[[ 6  7  8]
 [ 0 -2 -3]
 [ 4 -5 -6]]
[[ 0 -2 10 -3]
 [ 4 -5 10 -6]]
[[ 0 -3]
 [ 4 -6]]


When we have multiple arrays, we can stack them together either row-wise or column-wise. Again, there are multiple functions for doing this. The ones shown here will generally be versatile enough, and you can use others as well. Again, the main thing to keep in mind is to make sure that the dimensions match up. Some functions will accept 1D arrays as arguments as well.

In [6]:
B = np.array([[1,2],
              [3,4]])
C = np.array([[5,6],
              [7,8]])
d = np.array([9,10])

print(np.concatenate((B,C), axis=1))  # concatenate arrays column-wise
print(np.concatenate((B,C)))          # concatenate arrays row-wise (default axis=0)
print(np.row_stack((B,d)))            # stack rows together, inc. 1D arrays
print(np.column_stack((B,C,d)))       # stack columns together

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 1  2]
 [ 3  4]
 [ 9 10]]
[[ 1  2  5  6  9]
 [ 3  4  7  8 10]]


Such concatenation can also be represented in math in the form of *block matrices*, assuming all the constituent matrices are defined and of the proper size. The examples above are represented by the matrices $\begin{bmatrix} B & C \end{bmatrix}$, $\begin{bmatrix} B \\ C \end{bmatrix}$, $\begin{bmatrix} B & \mathbf d \end{bmatrix}$, and $\begin{bmatrix} B & C & \mathbf d \end{bmatrix}$, respectively.

The last useful manipulation function that we will mention here is *reshaping*. A $m \times n$ array can be reshaped into a $p \times q$ array as long as $mn=pq$. You can think of reshaping in NumPy as taking an array's entries, row by row, and then filling in the new array, also row by row. 

In [7]:
print(np.reshape(A, (3,2)))   # reshape A to be a 3x2 array
print(np.reshape(B, (4,1)))   # reshape B to be a 4x1 array
print(np.reshape(C, (1,4)))   # reshape C to be a 1x4 array
print(np.reshape(d, (1,2)))   # reshape d to be a 1x2 array (we go from 1D to 2D!)

[[ 0 -2]
 [-3  4]
 [-5 -6]]
[[1]
 [2]
 [3]
 [4]]
[[5 6 7 8]]
[[ 9 10]]


## Special Matrices (NumPy)

We sometimes refer to the *diagonal* entries of a matrix. These entries are the ones indexed by $A_{i,i}$. A square ($n \times n$) matrix is **diagonal** if all of its non-diagonal (off-diagonal) entries are 0: $A_{i,j} = 0$. An **identity matrix** is a diagonal matrix in which all diagonal entries are 1: $A_{i,i} = 1$. Both are easily defined in NumPy, along with some related functionalities.

In [8]:
print(np.diag([1,2,3]))   # create a diagonal matrix 
print(np.diag(A))         # same function can be used to extract diagonal entries of a given matrix
print(np.identity(3))     # create a 3x3 identity matrix
print(np.eye(3))          # same as above
print(np.eye(3,M=4))      # can also create rectangular "identity matrices"
print(np.eye(3,M=4,k=1))  # or place the diagonal entries off the main

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[ 0 -5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


NumPy makes it easy to obtain matrices of all-zeros and matrices of all-ones.

In [9]:
print("A 2x3 zeros matrix:\n", np.zeros([2,3]))
print("A 4x2 ones matrix:\n", np.ones([4,2]))

A 2x3 zeros matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
A 4x2 ones matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Matrix Operations

Matrices have several different associated operations, some of which extend naturally from the vector versions.

### Transpose

For vectors, the transpose operation transforms column vectors into row vectors and vice versa. The transpose of a matrix can be thought of as applying the vector transpose to each of the matrix's columns (or rows) individually. Column $i$ of $A$ becomes row $i$ of $A^\top$; row $j$ of $A$ becomes column $j$ of $A^\top$. In other words, $A^\top_{i,j} = A_{j,i}$. If $A$ is $m \times n$, $A^\top$ is $n \times m$. Note that $(A^\top)^\top = A$.

In [10]:
print(A)
print(A.T)

[[ 0 -2 -3]
 [ 4 -5 -6]]
[[ 0  4]
 [-2 -5]
 [-3 -6]]


A $n \times n$ matrix $S$ that satisfies $S^\top = S$, or equivalently $S_{i,j} = S_{j,i}$, is called a **symmetric matrix**.

### Scalar-matrix multiplication and matrix addition

These two operations are nearly identical to those for vectors. Multiplying a matrix by a scalar means multiplying every individual element by that scalar. Adding two $m \times n$ matrices means adding each corresponding element together. Similar properties (commutativity, etc.) also hold. Lastly, since these operations are implemented element-wise, they are compatible with the transpose operation as follows:

* $(\alpha A)^\top = \alpha A^\top$
* $(A+B)^\top = A^\top + B^\top$

Both operations are implemented easily in NumPy.

In [11]:
print(2*B)
print(B+C)
print(np.add(B,C))  # same as above

[[2 4]
 [6 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


### Matrix-vector multiplication

A $m \times n$ matrix $A$ may be multiplied with a column $n$-vector $\mathbf x$. The result is a column $m$-vector $\mathbf y = A \mathbf y$.

In NumPy, `dot`, `matmul`, and `@` can be repurposed to matrix-vector multiplication. The matrix (2D array) must be the first argument and the vector (1D array) must be the second.

In [12]:
A = np.array([[1,2,3],
              [4,5,6]])
b = np.array([7,8,9])

print(np.dot(A,b))
print(np.matmul(A,b))
print(A @ b)

[ 50 122]
[ 50 122]
[ 50 122]


### Matrix-matrix multiplication

Matrix-matrix multiplication is really a generalization of matrix-vector multiplication. The product of two matrices, an $m \times n$ matrix $A$ and an $n \times p$ matrix $B$ is an $m \times p$ matrix $C = AB$.

In [13]:
C = np.array([[-1,2],
              [3,-4],
              [-5,6]])

print(np.dot(A,C))
print(np.matmul(A,C))
print(A@C)

[[-10  12]
 [-19  24]]
[[-10  12]
 [-19  24]]
[[-10  12]
 [-19  24]]


In [17]:
# PS2 Problem 2.1

A=np.array([[-3,1,4],
            [1,7,2],
            [0,5,2]])
B=np.array([[1,2],
            [1,0],
            [1,-1]])
C=np.array([[1,0],
            [0,-1]])

print(2*C)
print(A@A)
print(A@B)
print(B@C)
print(A@B@C)
# Invalid
# print(C@A)
# print(C@B@A)

[[ 2  0]
 [ 0 -2]]
[[10 24 -2]
 [ 4 60 22]
 [ 5 45 14]]
[[  2 -10]
 [ 10   0]
 [  7  -2]]
[[ 1 -2]
 [ 1  0]
 [ 1  1]]
[[ 2 10]
 [10  0]
 [ 7  2]]


The following are properties of matrix-matrix (and matrix-vector) multiplication:

* Associativity: $(AB)C = A(BC)$
* Identity: $AI = IA = A$
* Distributivity over addition: $A(B+C) = AB + AC$, $(A+B)C = AC + BC$
* Transpose: $(AB)^\top = B^\top A^\top$

The last property may be counterintuitive; the transpose of a product is the reverse product of the transposes. In addition, notice that commutativity is not present. Matrix multiplication is *not* commutative in general: $AB \neq BA$. In fact, if either $A$ or $B$ is not square, one of the two products is generally not even defined.